[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "prosepctorLandUse"
version = "0.0.1"
description = "Prospector for extracting and synthesizing land use data"
authors = [
  { name = "GoldenPlanetaryHealthLab" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "pip",
    "python-dotenv",
    "ruff",
]
requires-python = "~=3.14.0"


[tool.ruff]
line-length = 99
src = ["prosepctorLandUse"]
include = ["pyproject.toml", "prosepctorLandUse/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["prosepctorLandUse"]
force-sort-within-sections = true

